import type {Metadata} from 'next';
import localFont from 'next/font/local';
import { Montserrat } from 'next/font/google'
import './globals.css';
import Link from 'next/link';

const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

// If loading a variable font, you don't need to specify the font weight
const montserrat = Montserrat({
    subsets: [],
    display: 'swap',
  })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className='p-6'>
            <body
                className={`${montserrat.className} ${geistMono} antialiased`}
            >
                <nav>
                    <ul className='flex gap-6'>
                        <li>
                            <Link href='/'>Home</Link>
                        </li>
                        <li>
                            <Link prefetch={false} href='/about'>About</Link>
                        </li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}
