import type {Metadata} from 'next';
import Image from 'next/image';
import {Quicksand} from 'next/font/google';
import './globals.css';
import Logo from '@/assets/images/logo-inverted.png';
import NavItem from '@/components/NavItem';
import MobileItem from '@/components/MobileItem';

const quickSand = Quicksand({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    style: ['normal'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang='en'>
            <body className={`${quickSand.className} antialiased`}>
                <main>
                    <header className='text-zinc-200'>
                        <nav className='sticky flex top-0 bg-gradient-to-r from-rose-500 to-pink-500'>
                            <div className='flex items-center p-2 gap-2'>
                                <Image
                                    src={Logo}
                                    alt='The site logo'
                                    width={50}
                                />
                                <div className='font-bold text-2xl'>
                                    tw:<span className='text-sky-900'>mf</span>
                                </div>
                            </div>
                            {/* Mobile burger nav */}
                            <MobileItem />

                            {/* Desktop Navigation */}
                            <div className='md:flex flex-1 hidden items-center justify-end'>
                                <NavItem label='Home' />
                                <NavItem label='Line Up' />
                                <NavItem label='Tickets' />
                                <div className='group relative flex h-full items-center p-4 cursor-pointer font-bold text-pink-200 hover:text-zinc-200 hover:bg-white/10 transition-colors ease-in-out'>
                                    <span>Parent Menu</span>
                                    <div className='group-hover:block hidden absolute top-full bg-pink-500 right-0 whitespace-nowrap rounded-b-md text-right'>
                                        <div className='p-4 font-bold hover:bg-white/5 hover:text-zinc-200 transition-colors ease-in-out cursor-pointer text-pink-200'>
                                            <span>Single day ticket</span>
                                        </div>
                                        <div className='p-4 font-bold hover:bg-white/5 hover:text-zinc-200 transition-colors ease-in-out cursor-pointer text-pink-200'>
                                            <span>7 day ticket</span>
                                        </div>
                                    </div>
                                </div>
                                <NavItem label='Support' />
                            </div>
                        </nav>
                    </header>
                    {children}
                </main>
            </body>
        </html>
    );
}
